name: Create Build

on:
  workflow_dispatch:
  push:
    tags:
      - "*"  # This triggers the workflow when any tag is created

jobs:
  build:
    name: Build and Create Artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Node.js (if your project is Node.js based, adjust accordingly)
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Adjust based on your project's requirements

      # Example build step (adjust for your project type)
      - name: Install dependencies
        run: npm install # Adjust this if you're using another build system

      - name: Build the project
        env:
          VITE_APP_VERSION: ${{ github.ref_name }}
          VITE_BASE_URL: ${{ steps.deployment.outputs.page_url }}
        run: |
          echo "App Version: ${{ env.VITE_APP_VERSION }}"
          npm run build

      - name: Create build output directory
        run: mkdir -p build

      - name: Copy build files to the output directory
        run: cp -r dist/* build/  # Adjust the path to your build output

      - name: Upload the build folder as an artifact (not a ZIP)
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ github.ref_name }}
          path: build/
