name: Tagging the Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  tag_version:
    name: Create Git Tag
    runs-on: ubuntu-latest

    steps:

      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Fetch tags from remote
        run: git fetch --tags

      - name: Get the Next Version
        id: version
        run: |
          # Get the latest tag
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "0.0.0")
          echo "Latest Tag: $latest_tag"

          # Increment the last number
          next_version=$(echo $latest_tag | awk -F. '{$NF+=1} 1' OFS=.)
          echo "Next Version: $next_version"
          echo "next_version=$next_version" >> $GITHUB_ENV

      # Create a tag and push it to the repository
      - name: Create Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag ${{env.next_version}}
          git push origin ${{env.next_version}}

      - name: Save the version number
        run: |
          echo "VITE_APP_VERSION=${{env.next_version}}" >> version.env
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add version.env
          git commit -m chore: update version.env for version ${{env.next_version}}"
          git push

        
