name: Create a Tag

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name (Leave empty to auto-increment from the latest tag)'
        required: false
        default: ''
  push:
    branches:
      - main

jobs:
  tag_version:
    name: Create Git Tag
    runs-on: ubuntu-latest

    steps:

      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Fetch tags from remote
        run: git fetch --tags

      - name: Get the Next Version
        id: version
        run: |
          # Check if tag_name is provided from workflow_dispatch input
          if [[ -z "${{ github.event.inputs.tag_name }}" ]]; then
            # No tag name provided, get the latest tag and increment
            latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "0.0.0")
            echo "Latest Tag: $latest_tag"

            # Increment the last number
            next_version=$(echo $latest_tag | awk -F. '{$NF+=1} 1' OFS=.)
            echo "Next Version: $next_version"
            echo "next_version=$next_version" >> $GITHUB_ENV
          else
            # Use provided tag_name
            echo "Using provided tag: ${{ github.event.inputs.tag_name }}"
            echo "next_version=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV
          fi

      # Create a tag and push it to the repository
      - name: Create Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag ${{env.next_version}}
          git push origin ${{env.next_version}}
